import { useMemo, useState } from 'react'
import { ArrowLeft, BookOpen, Check, Compass, GraduationCap, LineChart, ShieldCheck, Target, UserRoundSearch } from 'lucide-react'
import { Link } from 'react-router-dom'
import { assessCompass, scoreLinkedInAudit, type CompassInput, type ScoreItem } from '../lib/careerLogic'
import './career-pages.css'

const blankCompass: CompassInput = {
  stage: '', specialty: '', experience: '', currentField: '', targetField: '', goal: '', challenge: '', skills: '', targetSkills: '', evidence: '',
}

function PageIntro({ eyebrow, title, description, badge }: { eyebrow: string; title: string; description: string; badge?: string }) {
  return <header className="career-page-intro"><span className="eyebrow"><Compass size={15}/>{eyebrow}</span>{badge && <span className="career-badge">{badge}</span>}<h1>{title}</h1><p className="hero-lead">{description}</p></header>
}

function SectionHeading({ eyebrow, title, text }: { eyebrow?: string; title: string; text?: string }) {
  return <div className="career-section-heading">{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2>{text && <p>{text}</p>}</div>
}

function LocalPrivacyNote({ children = 'المدخلات تبقى في هذه الصفحة فقط ولا تُرسل إلى الخادم. لا تكتب أسماء مرضى أو بيانات سرية عن جهة العمل.' }: { children?: string }) {
  return <div className="career-privacy-note"><ShieldCheck size={17}/><span>{children}</span></div>
}

export function CareerJourneyHome() {
  return <>
    <section className="hero wrap career-home-hero">
      <div className="hero-copy"><span className="eyebrow"><span className="eyebrow-dot"/> مجتمع السيطرة المهنية · للمهنيين الصحيين</span><h1>من خبرتك الحالية،<br/><em>إلى خطوة مهنية أوضح.</em></h1><p className="hero-lead">مساحة مهنية آمنة للعاملين في الرعاية الصحية والخريجين الجدد: أدوات لاتخاذ قرار واعٍ، ومحتوى موثق، وزمالة مهنية، وورش تتصل بواقع العمل.</p><div className="hero-actions"><Link className="btn btn-primary" to="/career-journey">ابدأ رحلتك المهنية <ArrowLeft size={16}/></Link><Link className="btn btn-quiet" to="/career-compass">جرّب البوصلة <Compass size={16}/></Link></div><div className="career-home-trust"><span><ShieldCheck size={15}/> الخصوصية أولاً</span><span><BookOpen size={15}/> مصادر موثوقة</span><span><Target size={15}/> خطوات قابلة للتجربة</span></div></div>
      <div className="career-home-map" aria-label="خريطة من خمس خطوات للرحلة المهنية"><span className="map-orbit map-orbit-one"/><span className="map-orbit map-orbit-two"/><div className="map-center"><Compass size={40}/><b>خطوتك<br/>القادمة</b></div><span className="map-node map-node-a">اعرف موقعك</span><span className="map-node map-node-b">اختبر اتجاهاً</span><span className="map-node map-node-c">وثّق الأثر</span><span className="map-node map-node-d">تعلّم وتواصل</span></div>
    </section>
    <section className="trust-strip"><div className="wrap trust-inner"><span>ماذا تجد هنا؟</span><b><Compass size={16}/> بوصلة عملية</b><i/><b><BookOpen size={16}/> مكتبة مهنية موثقة</b><i/><b><GraduationCap size={16}/> تعلم وورش</b><i/><b><ShieldCheck size={16}/> مجتمع يحترم الخصوصية</b></div></section>
    <main className="career-page wrap"><section className="career-path-block"><SectionHeading eyebrow="Entry point → Career journey" title="رحلة مهنية، لا صفحة تعريف فقط" text="ابدأ بسؤال واحد واضح، ثم انتقل من الاستكشاف إلى التجربة والدليل. لا تحتاج إلى معرفة كل الإجابات قبل أن تبدأ."/><div className="career-step-grid"><article className="career-step-card career-step-feature"><span className="career-step-number">01</span><Compass/><h3>افهم موقعك الحالي</h3><p>مرحلتك، خبرتك، مجال عملك، مهاراتك، وما الذي تريد تغييره فعلاً.</p><Link to="/career-compass">افتح البوصلة المهنية <ArrowLeft size={15}/></Link></article><article className="career-step-card"><span className="career-step-number">02</span><UserRoundSearch/><h3>حوّل المهارة إلى دليل</h3><p>سجّل ما فعلته، ولماذا يهم، وما الذي تستطيع إثباته من دون خرق السرية.</p><Link to="/achievement-portfolio">ابنِ ملف إنجازاتك <ArrowLeft size={15}/></Link></article><article className="career-step-card"><span className="career-step-number">03</span><LineChart/><h3>اقرأ الإشارات لا الضجيج</h3><p>قارن متطلبات الوظائف والمصادر الرسمية قبل أن تستنتج اتجاه السوق.</p><Link to="/saudi-labor-market-radar">افتح رادار السوق <ArrowLeft size={15}/></Link></article><article className="career-step-card"><span className="career-step-number">04</span><BookOpen/><h3>تعلّم وجرّب</h3><p>اقرأ المقالات، أجرِ تدقيقاً ذاتياً، ثم اتفق على تجربة مهنية صغيرة.</p><Link to="/articles">استكشف المكتبة <ArrowLeft size={15}/></Link></article></div></section>
      <section className="career-track-band"><div><span className="eyebrow">لكل مرحلة مدخلها</span><h2>ما الذي تريد إنجازه الآن؟</h2><p>اختر المسار الأقرب إلى قرارك الحالي. الأدوات لا تجمع بياناتك المهنية ولا تتنبأ بالتوظيف أو الترقية.</p></div><div className="career-track-links"><Link to="/fresh-graduate">حديث التخرج <ArrowLeft size={15}/></Link><Link to="/linkedin-audit">تحسين LinkedIn <ArrowLeft size={15}/></Link><Link to="/value-economy">القيمة المهنية والتفاوض <ArrowLeft size={15}/></Link><Link to="/promotion-intelligence">الاستعداد للترقية <ArrowLeft size={15}/></Link><Link to="/innovation-rd">الابتكار والبحث والتطوير <ArrowLeft size={15}/></Link><Link to="/ai-career-leverage">العمل مع AI <ArrowLeft size={15}/></Link></div></section>
      <section className="career-workshop-teaser"><div><span className="eyebrow">ورشة تطبيقية</span><h2>اختراق LinkedIn: من ملف ساكن إلى أصل مهني</h2><p>مسار ذاتي يتضمن وحدات، أمثلة، تمارين، قائمة تحقق وخطة عمل. لا يوجد موعد أو بث معلن حالياً.</p></div><Link className="btn btn-primary" to="/linkedin-workshop">ابدأ الورشة <ArrowLeft size={16}/></Link></section>
      <section className="career-community-callout"><div><span className="eyebrow">ما الذي يستطيع العضو فعله؟</span><h2>يتواصل، يتعلّم، يشارك خبرته، ويطلب مساحة للتفكير.</h2><p>داخل المجتمع توجد ملفات مهنية، تواصل وزمالة، كوتشنج اختياري، ومركز تعلم للأعضاء المعتمدين. لا تُشارك بيانات أو صور المرضى في أي مساحة.</p></div><div className="career-community-actions"><Link className="btn btn-primary" to="/register">انضم للمجتمع <ArrowLeft size={15}/></Link><Link className="btn btn-outline" to="/learning">مركز التعلّم <ArrowLeft size={15}/></Link><Link className="text-link" to="/about">كيف يعمل المجتمع؟ <ArrowLeft size={14}/></Link></div></section>
    </main>
  </>
}

export function CareerJourneyPage() {
  return <main className="public-page wrap career-page"><nav className="breadcrumbs"><Link to="/">الرئيسية</Link><span>/</span><span>الرحلة المهنية</span></nav><PageIntro eyebrow="خارطة عملية" title="رحلتك المهنية تبدأ بالوضوح، ثم التجربة" description="ابدأ بتحديد وضعك، اجمع أدلة على قدراتك، افحص اتجاهك في ضوء مصادر موثوقة، ثم اختر تجربة واحدة قابلة للتقييم. القرار النهائي لك؛ الأدوات هنا لتنظيم التفكير لا لاستبداله."/><div className="career-journey-timeline">{[
    ['01','تحديد نقطة البداية','استخدم البوصلة لوصف المرحلة والتخصص والمجال الحالي والهدف والتحدي. إذا غابت البيانات المهمة فلن تخترع الأداة نتيجة.','/career-compass','ابدأ البوصلة'],
    ['02','اختبار المهارة والاتجاه','اختر مهارة مستهدفة، وراجع أكثر من وصف وظيفي ومصدر رسمي، ثم اسأل ممارساً في الدور.','/saudi-labor-market-radar','راجع رادار السوق'],
    ['03','إثبات القيمة','حوّل العمل إلى سياق ودور وفعل ونتيجة ودليل صالح للمشاركة. اترك أي معلومة سرية خارج الملف.','/achievement-portfolio','ابنِ ملف الإنجازات'],
    ['04','تحسين الظهور والتواصل','راجع صفحة LinkedIn، وصغ تموضعاً محدداً، ثم شارك فكرة مهنية مفيدة من دون ادعاء أو كشف معلومات.','/linkedin-audit','افحص ملفك المهني'],
    ['05','تعلّم ومراجعة','نفذ خطة 90 يوماً، وناقش التقدم مع شخص موثوق، وراجع قرارك بعد ظهور دليل جديد.','/articles','اقرأ المقالات'],
  ].map(([number, title, text, url, label]) => <article className="career-timeline-row" key={number}><span className="career-timeline-number">{number}</span><div><h2>{title}</h2><p>{text}</p><Link to={url}>{label} <ArrowLeft size={14}/></Link></div></article>)}</div><div className="career-privacy-note"><ShieldCheck size={18}/><span>المسارات لا تضمن وظيفة أو ترقية أو زيادة دخل. استخدم بيانات عامة ومهنية فقط، ولا تضع أسماء مرضى أو معلومات عمل سرية.</span></div></main>
}

export function CareerCompassPage() {
  const [input, setInput] = useState<CompassInput>(blankCompass)
  const [submitted, setSubmitted] = useState(false)
  const result = useMemo(() => submitted ? assessCompass(input) : null, [input, submitted])
  const update = (key: keyof CompassInput, value: string) => { setInput(current => ({ ...current, [key]: value })); setSubmitted(false) }
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true) }
  const reset = () => { setInput(blankCompass); setSubmitted(false) }

  return <main className="public-page wrap career-page"><nav className="breadcrumbs"><Link to="/">الرئيسية</Link><span>/</span><Link to="/career-journey">الرحلة المهنية</Link><span>/</span><span>البوصلة</span></nav><PageIntro eyebrow="أداة استكشاف ذاتي · MVP" title="البوصلة المهنية" description="أدخل معلومات كافية عن مرحلتك واتجاهك لتحصل على ملخص منظم، وفجوات مهارية قابلة للاختبار، وخطوات 90 يوماً و12 شهراً. لا تدّعي الأداة أنها تعرف سوقك أو تتنبأ بمستقبلك." badge="لا حساب مطلوب"/><LocalPrivacyNote/>
    <form className="career-form-card" onSubmit={submit}><div className="career-form-heading"><span className="career-form-icon"><Compass size={19}/></span><div><h2>ارسم نقطة البداية والوجهة</h2><p>الحقول كلها مطلوبة حتى لا نبني نتيجة على افتراضات.</p></div></div><div className="career-form-grid">
      <label>المرحلة المهنية<select required value={input.stage} onChange={event => update('stage', event.target.value)}><option value="">اختر المرحلة</option><option>طالب/ـة</option><option>حديث/ـة تخرج</option><option>بداية المسار</option><option>منتصف المسار</option><option>قيادة أو تخصص متقدم</option><option>انتقال مهني</option></select></label>
      <label>التخصص<input required value={input.specialty} onChange={event => update('specialty', event.target.value)} maxLength={120} placeholder="مثال: تمريض، صيدلة، معلوماتية صحية"/></label>
      <label>سنوات الخبرة<input required type="number" inputMode="numeric" min="0" max="80" step="1" value={input.experience} onChange={event => update('experience', event.target.value)} placeholder="0"/></label>
      <label>المجال الحالي<input required value={input.currentField} onChange={event => update('currentField', event.target.value)} maxLength={140} placeholder="الدور أو البيئة الحالية"/></label>
      <label>المجال المستهدف<input required value={input.targetField} onChange={event => update('targetField', event.target.value)} maxLength={140} placeholder="دور أو مجال تريد استكشافه"/></label>
      <label>الهدف المهني<textarea required value={input.goal} onChange={event => update('goal', event.target.value)} maxLength={280} rows={2} placeholder="ما التغير الذي تريد رؤيته خلال عام؟"/></label>
      <label>التحدي الحالي<textarea required value={input.challenge} onChange={event => update('challenge', event.target.value)} maxLength={280} rows={2} placeholder="ما الذي يبطئ تقدمك الآن؟"/></label>
      <label>المهارات الحالية<textarea required value={input.skills} onChange={event => update('skills', event.target.value)} maxLength={500} rows={3} placeholder="افصل المهارات بفاصلة؛ أضف مستوى أو مثالاً عند الإمكان"/></label>
      <label>المهارات التي يتطلبها الاتجاه المستهدف<textarea required value={input.targetSkills} onChange={event => update('targetSkills', event.target.value)} maxLength={500} rows={3} placeholder="اكتب مهارات رأيتها في وصف وظيفي أو مصدر موثوق"/></label>
      <label className="career-form-wide">مثال مختصر على دليل إنجاز<textarea required value={input.evidence} onChange={event => update('evidence', event.target.value)} maxLength={360} rows={3} placeholder="مشكلة عامة، دورك، نتيجة، ودليل يمكن مشاركته من دون معلومات سرية"/></label>
    </div><div className="career-form-actions"><button className="btn btn-primary" type="submit">حلّل مدخلاتي <ArrowLeft size={16}/></button><button className="btn btn-quiet" type="button" onClick={reset}>مسح المدخلات</button></div></form>
    {submitted && result?.report && <section className="career-report" aria-live="polite"><div className="career-report-heading"><span className="eyebrow"><Check size={14}/> تقرير مبني على مدخلاتك</span><h2>ماذا تعني نقطة البداية هذه؟</h2><p>هذه خريطة للتجربة والمراجعة، وليست توصية مهنية ملزمة أو تنبؤاً بالطلب.</p></div><article className="career-report-card"><h3>موقعك المهني الحالي</h3><p>{result.report.position}</p></article><article className="career-report-card"><h3>اتجاه السوق الذي اخترت اختباره</h3><p>{result.report.marketDirection}</p><Link to="/saudi-labor-market-radar">افحص المصادر الرسمية في رادار السوق <ArrowLeft size={14}/></Link></article><article className="career-report-card"><h3>فجوات المهارات التي أدخلتها</h3><ul>{result.report.skillGaps.map((skill, index) => <li key={`${skill}-${index}`}>{skill}</li>)}</ul><p className="career-small-note">تحقق من كل مهارة باستخدام إعلان وظيفي أو معيار مهني، ثم اختر فرصة ممارسة يمكن إثباتها.</p></article><article className="career-report-card"><h3>اتجاهات مهنية ممكنة للاختبار</h3><ol>{result.report.directions.map((direction, index) => <li key={index}>{direction}</li>)}</ol></article><article className="career-report-card"><h3>خطة الـ 90 يوماً</h3><ol>{result.report.next90Days.map((step, index) => <li key={index}>{step}</li>)}</ol></article><article className="career-report-card"><h3>منظور 12 شهراً</h3><ol>{result.report.next12Months.map((step, index) => <li key={index}>{step}</li>)}</ol></article><article className="career-positioning-output"><span className="eyebrow">مسودة تموضع مهني</span><p>«{result.report.positioningStatement}»</p><span className="career-small-note">راجعها، واحذف أي معلومة سرية، وبدّل العبارات العامة بدليل قابل للتحقق.</span></article><div className="career-next-links"><Link className="btn btn-outline" to="/achievement-portfolio">وثّق إنجازاتك <ArrowLeft size={15}/></Link><Link className="btn btn-primary" to="/professional-positioning">حسّن تموضعك <ArrowLeft size={15}/></Link></div></section>}
    {submitted && result?.missing.length ? <div className="career-incomplete" role="alert"><h2>البيانات لا تكفي بعد لإخراج نتيجة</h2><p>أكمل هذه الحقول؛ لن نخترع قيمة مفقودة:</p><ul>{result.missing.map(item => <li key={item}>{item}</li>)}</ul></div> : null}
    <section className="career-what-next"><SectionHeading eyebrow="بعد التقرير" title="اختر تجربة صغيرة، لا قفزة عمياء" text="ناقش الاتجاه مع شخص يعمل فيه، راجع متطلبات الوظائف الفعلية، واختر تجربة محدودة ثم قِس ما تعلمته."/><div className="career-inline-links"><Link to="/articles/career-compass">اقرأ الدليل البحثي للبوصلة المهنية <ArrowLeft size={14}/></Link><Link to="/linkedin-workshop">ورشة LinkedIn <ArrowLeft size={14}/></Link><Link to="/career-journey">العودة إلى الرحلة <ArrowLeft size={14}/></Link></div></section>
  </main>
}

const auditCatalog = [
  { id: 'headline', label: 'Headline', fix: 'اكتب دورك أو مجال تخصصك والجمهور أو المشكلة والقيمة التي تستطيع دعمها بدليل؛ لا تحشو كلمات مفتاحية.' },
  { id: 'about', label: 'About', fix: 'رتّب فقرتك إلى: من تخدم، ما القدرة التي تقدمها، دليل موجز، وما النوع الذي تريد استكشافه.' },
  { id: 'experience', label: 'Experience', fix: 'صف مسؤولياتك بصيغة الفعل والسياق والنتيجة، وافصل ما أنجزته عن وصف جهة العمل.' },
  { id: 'achievements', label: 'Achievements', fix: 'أضف نتائج قابلة للتحقق مع خط أساس وسياق وحدود قياس، ولا تنسب للفرد أثراً صنعه فريق كامل.' },
  { id: 'skills', label: 'Skills', fix: 'رتب المهارات التي تستخدمها فعلياً، واطلب تأييداً صادقاً ممن عاين العمل مباشرة.' },
  { id: 'featured', label: 'Featured', fix: 'اعرض نموذج عمل عاماً أو منشوراً مهنياً مفيداً تملك حق مشاركته.' },
  { id: 'portfolio', label: 'Portfolio', fix: 'أنشئ عينة عمل منزوعة الهوية والمعلومات السرية؛ اشرح المشكلة والطريقة والقرار.' },
  { id: 'content', label: 'Content', fix: 'شارك فكرة تعليمية أو تأملاً مهنياً محدداً يضيف قيمة، بدلاً من منشورات عامة متكررة.' },
  { id: 'positioning', label: 'Positioning', fix: 'اجعل هدف الملف متسقاً مع المسار الذي تريد اختباره، وراجع توافق الأقسام واللغة.' },
]

function LinkedInAuditPage() {
  const [ratings, setRatings] = useState<Record<string, number | null>>(() => Object.fromEntries(auditCatalog.map(item => [item.id, null])))
  const [submitted, setSubmitted] = useState(false)
  const items: ScoreItem[] = useMemo(() => auditCatalog.map(item => ({ ...item, value: ratings[item.id] ?? null })), [ratings])
  const result = useMemo(() => submitted ? scoreLinkedInAudit(items) : null, [submitted, items])
  return <main className="public-page wrap career-page"><nav className="breadcrumbs"><Link to="/">الرئيسية</Link><span>/</span><Link to="/career-journey">الرحلة المهنية</Link><span>/</span><span>تدقيق LinkedIn</span></nav><PageIntro eyebrow="تقييم عملي من 9 محاور" title="LinkedIn Audit" description="قيّم وضوح ملفك واكتماله بالأدلة. الدرجة تساعدك على ترتيب التحرير فقط؛ لا تقيس فرص التوظيف ولا تمثل خوارزمية المنصة."/><LocalPrivacyNote/>
    <form className="career-audit-list" onSubmit={event => { event.preventDefault(); setSubmitted(true) }}>{auditCatalog.map(item => <fieldset className="career-audit-row" key={item.id}><legend><b>{item.label}</b><span>{item.fix}</span></legend><div className="career-rating-scale" role="radiogroup" aria-label={`تقييم ${item.label}`}>{[1,2,3,4,5].map(value => <label className={ratings[item.id] === value ? 'selected' : ''} key={value}><input type="radio" name={item.id} value={value} checked={ratings[item.id] === value} onChange={() => { setRatings(current => ({ ...current, [item.id]: value })); setSubmitted(false) }}/><span>{value}</span></label>)}</div><small>1 = يحتاج إلى بناء · 5 = واضح ومدعوم بدليل</small></fieldset>)}<div className="career-form-actions"><button className="btn btn-primary" type="submit">احسب الدرجة والأولويات <ArrowLeft size={15}/></button><button className="btn btn-quiet" type="button" onClick={() => { setRatings(Object.fromEntries(auditCatalog.map(item => [item.id, null]))); setSubmitted(false) }}>إعادة التدقيق</button></div></form>
    {submitted && !result && <div className="career-incomplete" role="alert"><h2>أكمل المحاور التسعة</h2><p>كل محور يحتاج إلى تقدير واحد قبل أن نرتب الأولويات.</p></div>}
    {result && <section className="career-audit-result" aria-live="polite"><div className="career-score-orbit"><span>درجة الاكتمال الذاتي</span><strong>{result.score}<small>/100</small></strong><span>ليست درجة توظيف أو ترتيباً في LinkedIn</span></div><div className="career-audit-priorities"><SectionHeading eyebrow="أولويات التحرير" title="ابدأ بأكبر ثلاث فجوات" text="الأولوية مبنية على تقييمك أنت؛ أعد التقييم بعد التحرير."/><ol>{result.priorities.map((item, index) => <li key={item.id}><b>{index + 1}. {item.label}</b><span>{item.fix}</span></li>)}</ol><h3>خطة عمل لثلاثة أسابيع</h3><ul>{result.actionPlan.map(step => <li key={step}>{step}</li>)}</ul></div></section>}
    <section className="career-workshop-teaser"><div><span className="eyebrow">حوّل التدقيق إلى تطبيق</span><h2>ورشة: من ملف ساكن إلى أصل مهني</h2><p>طبّق التوصيات في وحدات قصيرة، ثم ارجع إلى التقييم.</p></div><Link className="btn btn-primary" to="/linkedin-workshop">افتح الورشة <ArrowLeft size={15}/></Link></section>
  </main>
}

const graduatePhases = [
  { id: 'before', title: 'قبل التخرج', tasks: ['حدّث السيرة الذاتية بما فعلته فعلاً، وميّز التدريب عن الخبرة المستقلة.', 'راجع متطلبات الترخيص أو التسجيل المهني لدى الجهة الرسمية ذات الصلة.', 'اجمع 3 أمثلة على مهارات أو مشاريع تسمح بها سياسة الجهة التعليمية.', 'اطلب مراجعة من شخص يفهم الدور المستهدف، وحدّث ملف LinkedIn.'] },
  { id: 'days30', title: 'أول 30 يوماً', tasks: ['افهم نطاق دورك، المشرف المباشر، وقنوات السؤال والتصعيد.', 'دوّن توقعات النجاح للأسبوع الأول والشهر الأول واتفق عليها مع مديرك.', 'تعرف على إجراءات الخصوصية والسلامة والتوثيق الخاصة بجهة العمل.', 'سجّل الأسئلة المتكررة وما تعلمته، من دون أي بيانات مرضى أو معلومات تشغيلية سرية.'] },
  { id: 'days90', title: 'أول 90 يوماً', tasks: ['راجع التوقعات في الأسبوعين 4 و8 و12 مع المشرف.', 'اختر فجوة مهارة واحدة، وحدد تدريباً وممارسة وتغذية راجعة.', 'اطلب مسؤولية مناسبة لمستوى خبرتك؛ لا تتجاوز صلاحياتك المهنية.', 'اكتب ملخص تعلم يوضح فعلك والنتيجة والدليل المسموح بمشاركته.'] },
  { id: 'interview', title: 'أول مقابلة', tasks: ['حضّر أمثلة STAR: الموقف، المهمة، الفعل، النتيجة.', 'اقرأ وصف الوظيفة واربط كل مثال بمتطلب حقيقي.', 'تدرّب على سؤال عن تحدٍّ أو خطأ وما تعلمته منه.', 'اسأل عن الإشراف، توقعات أول 90 يوماً، الفريق، والفرص التعليمية.'] },
  { id: 'firstjob', title: 'أول وظيفة', tasks: ['راجع عقدك ووصف الدور والحقوق لدى مصدر رسمي أو مستشار مختص عند الحاجة.', 'اعرف حدود الدور وخطوات طلب الإشراف قبل أداء مهمة غير مألوفة.', 'أنشئ خطة تعلم أسبوعية واقعية مرتبطة باحتياج الدور.', 'ابنِ علاقة مهنية محترمة واطلب تغذية راجعة محددة.'] },
  { id: 'win', title: 'أول إنجاز', tasks: ['حدد مشكلة صغيرة ضمن نطاق صلاحيتك وبالتنسيق مع الفريق.', 'اتفق على معيار النجاح قبل التغيير.', 'قِس النتيجة بطريقة منصفة؛ لا تنسب أثر الفريق إلى فرد واحد.', 'وثّق الأثر بعد إخفاء أي معلومات سرية أو تخص المرضى.'] },
  { id: 'year', title: 'أول سنة', tasks: ['راجع ما تعلمته وما تريد الاستمرار فيه أو تغييره.', 'حدّث ملف الإنجازات والسيرة الذاتية بناءً على أدلة مسموح بها.', 'ناقش المسؤوليات القادمة أو التطور مع مديرك بموعد محدد.', 'حدّث خطة العام القادم بما يتوافق مع اهتماماتك وظروفك.'] },
]

function storedChecklist(key: string): string[] {
  try { const value = localStorage.getItem(key); const parsed = value ? JSON.parse(value) : []; return Array.isArray(parsed) ? parsed.filter(item => typeof item === 'string') : [] } catch { return [] }
}

export function FreshGraduatePage() {
  const [done, setDone] = useState<string[]>(() => storedChecklist('saytara-graduate-checklist-v1'))
  const [stage, setStage] = useState('')
  const [confidence, setConfidence] = useState('')
  const [assessmentShown, setAssessmentShown] = useState(false)
  const allTaskIds = graduatePhases.flatMap(phase => phase.tasks.map((_, index) => `${phase.id}-${index}`))
  const progress = Math.round((done.length / allTaskIds.length) * 100)
  function toggle(id: string) {
    setDone(current => {
      const next = current.includes(id) ? current.filter(item => item !== id) : [...current, id]
      try { localStorage.setItem('saytara-graduate-checklist-v1', JSON.stringify(next)) } catch { /* progress remains usable in memory */ }
      return next
    })
  }
  return <main className="public-page wrap career-page"><nav className="breadcrumbs"><Link to="/">الرئيسية</Link><span>/</span><Link to="/career-journey">الرحلة المهنية</Link><span>/</span><span>جاهزية حديث التخرج</span></nav><PageIntro eyebrow="Roadmap للخريج الصحي" title="جاهزية حديث التخرج" description="مسار عملي من قبل التخرج إلى أول سنة: خطّط، افهم توقعات العمل، ابنِ أمثلة مقابلة، ثم وثّق أول إنجاز بأمان."/><LocalPrivacyNote>حالة إنجاز قائمة التحقق تُحفظ محلياً على هذا المتصفح فقط. لا تُدخل بيانات تعريفية أو سرية؛ يمكنك مسح التقدم في أي وقت.</LocalPrivacyNote>
    <section className="career-assessment-card"><div><span className="eyebrow"><GraduationCap size={15}/> فحص سريع لبداية المسار</span><h2>ما الذي تحتاجه الآن؟</h2><p>اختر المرحلة ومدى ثقتك؛ سنرشدك إلى قسم البداية المناسب من هذا المسار فقط.</p></div><div className="career-assessment-controls"><label>مرحلتك الحالية<select value={stage} onChange={event => { setStage(event.target.value); setAssessmentShown(false) }}><option value="">اختر</option><option value="before">قبل التخرج</option><option value="interview">أستعد لمقابلة</option><option value="firstjob">في أول وظيفة</option><option value="year">أراجع عامي الأول</option></select></label><label>ما مدى وضوح خطوتك القادمة؟<select value={confidence} onChange={event => { setConfidence(event.target.value); setAssessmentShown(false) }}><option value="">اختر</option><option value="low">أحتاج إلى ترتيب الأساسيات</option><option value="mid">لدي اتجاه وأحتاج إلى دليل أو تغذية راجعة</option><option value="high">أريد توسيع المسؤولية أو التخصص</option></select></label><button className="btn btn-primary btn-small" type="button" onClick={() => setAssessmentShown(true)} disabled={!stage || !confidence}>اعرض نقطة البداية</button></div>{assessmentShown && <div className="career-assessment-result" role="status"><b>ابدأ من «{graduatePhases.find(item => item.id === stage)?.title}».</b><span>{confidence === 'low' ? 'ابدأ بالمهام الأولى في هذا القسم، ثم اطلب مراجعة من مشرف أو مرشد مهني.' : confidence === 'mid' ? 'سجّل مثالاً عملياً وتحقق من متطلبات الدور مع مصدر رسمي أو شخص يعمل فيه.' : 'استخدم قسم أول إنجاز وأول سنة لربط التوسع بدليل وتغذية راجعة.'}</span></div>}</section>
    <section className="career-checklist-card"><div className="career-checklist-top"><div><span className="eyebrow">قائمة التحقق · محفوظة محلياً</span><h2>تقدمك في المسار</h2></div><strong>{progress}%</strong></div><div className="career-progress-track"><span style={{ width: `${progress}%` }}/></div><div className="career-phase-list">{graduatePhases.map(phase => <details className="career-phase" key={phase.id} open={phase.id === stage}><summary><span>{phase.title}</span><small>{phase.tasks.filter((_, index) => done.includes(`${phase.id}-${index}`)).length}/{phase.tasks.length}</small></summary><div className="career-phase-tasks">{phase.tasks.map((task, index) => { const id = `${phase.id}-${index}`; return <label className={done.includes(id) ? 'is-done' : ''} key={id}><input type="checkbox" checked={done.includes(id)} onChange={() => toggle(id)}/><span>{task}</span></label>})}</div></details>)}</div><button className="btn btn-quiet" type="button" onClick={() => { setDone([]); try { localStorage.removeItem('saytara-graduate-checklist-v1') } catch { /* best-effort local reset */ } }}>مسح تقدم القائمة</button></section>
    <section className="career-template-grid"><SectionHeading eyebrow="قوالب قابلة للنسخ" title="أدوات صغيرة لأول مقابلة وأول إنجاز"/><details className="career-template"><summary>قالب التعريف المهني في 30 ثانية</summary><p>«أنا [تخصص/مرحلة]، أعمل/أتدرب في [سياق عام]. أركز على [قدرة مرتبطة بالدور]، وأستند إلى [مثال أو مشروع مسموح بمشاركته]. أبحث الآن عن فرصة لتطوير [اتجاه]». لا تذكر معلومات مريض أو جهة سرية.</p></details><details className="career-template"><summary>قالب STAR لمثال مقابلة</summary><p><b>الموقف:</b> ما السياق العام؟ <b>المهمة:</b> ما مسؤوليتك وحدودها؟ <b>الفعل:</b> ماذا فعلت أنت؟ <b>النتيجة:</b> ماذا تغير، وكيف عرفت؟ انسب جهد الفريق للجميع واحذف أي بيانات حساسة.</p></details><details className="career-template"><summary>قالب رسالة متابعة بعد مقابلة</summary><p>«شكراً لوقتكم اليوم. أقدّر توضيح [موضوع مهني]. زاد اهتمامي بالدور، وخصوصاً [متطلب محدد]. يسعدني تزويدكم بمعلومات إضافية عن [خبرة/مشروع مناسب]. مع التقدير، [اسمك]».</p></details><details className="career-template"><summary>مراجعة نهاية الشهر الأول</summary><p>ما توقعات الدور التي اتضحت؟ ما المهارة التي تدربت عليها؟ أين تحتاج إشرافاً؟ ما الدليل الذي يحق لك حفظه؟ ما السؤال الذي ستناقشه في اجتماع المتابعة؟</p></details></section>
    <section className="career-related-links"><SectionHeading eyebrow="تابع التعلّم" title="مقالات وورش مرتبطة بالخريج"/><div className="career-inline-links"><Link to="/articles/fresh-graduate">اقرأ مقال جاهزية الخريج <ArrowLeft size={14}/></Link><Link to="/linkedin-workshop">ورشة LinkedIn <ArrowLeft size={14}/></Link><Link to="/achievement-portfolio">ملف الإنجازات <ArrowLeft size={14}/></Link><Link to="/career-compass">البوصلة المهنية <ArrowLeft size={14}/></Link></div></section>
  </main>
}

export { LinkedInAuditPage }
